### ISSUE TITLE
[Bug]: Slow WriteLine

### ISSUE THREAD

**Issue by MichalNekvasil** [IFCjs/web-ifc#469]
### What is your idea?

Hello there. I'm trying to write some new lines to my IFC file, but basic approach seems to be very slow. I call CreateIfcEntity, and then I call WriteLine. 

Is there any way, to do it faster, like some "batchUpdate" or so?

Thank you very much. Have a nice day
Michal

**Comment by beachtom** [comment]
Do you mean slow in terms of performance, or do you mean in that it takes two function calls? Do you have anything you suggest that would improve it?

**Comment by MichalNekvasil** [comment]
I mean in terms of performance. I need to remove and add some lines in file and it took about 2-3 minutes if I do around 4000 loops containing DeleteLine and two WriteLines. I have no suggestions, I have not studied the inner code yet. Just asking, if there is already some ways to improve perfmormance.

**Comment by beachtom** [comment]
hmm I think this is a bug - it should be quicker than that.

Let me investigate. Any chance you can share a code snippet?

**Comment by MichalNekvasil** [comment]
There is a code snippet. I just try to replace "IFCCOMPLEXPROPERTY" with just "IFCPROPERTYSINGLEVALUE" and add relation ... hope this helps ... If you need some models too, it should be some models @LukasKStavario already sent you. Or I can send some to you if you want ...

`const loadData = async (modelID: number) => {
    let dataProps = await serializeProps(modelID, undefined, (p, t) => { console.log(p, ' z ', t) }, true);
    let results: any[] = [];
    let properties: any[] = [];
    let propSets: any[] = [];
    let relations: any[] = [];
    let propertyComplexs: any[] = [];

    if (dataProps) {

      let input = dataProps
      let propsArray: any[] = [];
      for (let key in input)
        propsArray.push(input[key]);

      propsArray.forEach((propRow: any, index: number) => {
        if (propRow.type === 'IFCPROPERTYSET') {
          // console.log(propRow);
          propSets.push(propRow);
        }
        else if (propRow.type === 'IFCCOMPLEXPROPERTY') {
          //console.log(propRow);
          propertyComplexs.push(propRow);
        }
        else if (propRow.type === 'IFCPROPERTYSINGLEVALUE') {
          // console.log(propRow);
          properties.push(propRow);
        }
        else if (propRow.type === 'IFCRELDEFINESBYPROPERTIES') {
          relations.push(propRow);
        }
        if (propsArray.length < 15000) {
          if (index % 50 === 0)
            console.log(index);
        }
        else {
          // if (index % 1000 === 0)
          //   console.log(index);
        }
      });
    }
    return { complexProps: propertyComplexs, propSets: propSets, properties: properties, relations: relations };
  }
  const exportModel = async () => {
    let data = await loadData(0);

    let newLines: any[] = [];
    let newPropsets: any[] = [];

    data.propSets.forEach(propSet => {
      let newPropsetHasProperties: any[] = [];
      propSet.HasProperties?.forEach((propS: any) => {
        //find property
        let prop = data.properties.find(x => x.expressID === propS);
        if (prop === undefined) {
          let complex = data.complexProps.find(x => x.expressID === propS);
          if (complex !== undefined) {
            let rel = data.relations.find(x => x.RelatingPropertyDefinition === propSet.expressID);
            let n = api?.CreateIfcEntity(0, WebIFC.IFCPROPERTYSET, IFCGuidConverter.compress(Guid.MakeNew().ToString()), { type: 5, value: rel.OwnerHistory },complex.Name, null, complex.HasProperties.map((x: any) =>
              ({ type: 5, value: x })
            ));

            newLines.push(n);
            api!.DeleteLine(0, complex.expressID);
            if (n)
              api?.WriteLine(0, n);


            let r = api?.CreateIfcEntity(0, WebIFC.IFCRELDEFINESBYPROPERTIES, IFCGuidConverter.compress(Guid.MakeNew().ToString()), { type: 5, value: rel.OwnerHistory }, null, null, rel.RelatedObjects.map((p: any) => ({ type: 5, value: p })), { type: 5, value: n?.expressID });
            if (r)
              api?.WriteLine(0, r);
          }
        }
        else {
          newPropsetHasProperties.push(propS);
        }
      });
    });

    let buffer = api!.SaveModel(0);
    handleDownload(buffer, 'test.ifc');
  }`

**Comment by beachtom** [comment]
Just to help me track it down - do you have any instrumentation you can add - just timing ticks - to show if it is CreateIfcEntity, DeleteLine or WriteLine that is taking the chunk of time?

**Comment by MichalNekvasil** [comment]
It is almost surely WiteLine. If I do not call WriteLine (I tried and commented it), it's very fast ...

**Comment by beachtom** [comment]
Ok so I think I have fixed this. At least I can now write 10k lines in 3.5s on my pc.

If not... can you re-open with a code that I can run and your model so I can try and replicate your exact problem

**Comment by LukasKStavario** [comment]
Sorry Tom, this does not work fine.
For small models (from one to 20 megabytes) the correction works - that means the speed was increased. But If I load model that have milion lines, every write line took so long time. Can you do anything with that? Or batch write might be the solution for our reason. Thank you.

**Comment by beachtom** [comment]
Can you share model/code you are running and I will do some more tests.

**Comment by LukasKStavario** [comment]
Code is same as here - https://github.com/IFCjs/web-ifc/issues/469#issuecomment-1697458284 is it clear?

And model I am uploading and send it to mail.

**Comment by LukasKStavario** [comment]
Hello, can it at least be said if it can be speeded up? Or if it will at least be possible to complete a batch write that would at least partially solve the problem?

**Comment by beachtom** [comment]
This should now be fixed. I also added a bulk method WriteLines(...) that takes an array of IfcLIneObject as a parameter.

But can you test the speed improvement with the normal method for me please? And re-open if still too slow

**Comment by LukasKStavario** [comment]
Hi Tom, on most of my models the speed improvment is really cool. But model that I have sent you still cannot reexport. Start of writing is very fast, but after 12K lines added, it freeze and one line took 5 second.

**Comment by beachtom** [comment]
OK so is it just one line that is slow and then it speeds up - or once it starts slowing down does it stay slow?

Have you tried the batch WriteLines method.

**Comment by LukasKStavario** [comment]
No,unfortunately the thing is that it stays slow, the first 12K rows take a second and the next 500 rows take an hour :/

**Comment by beachtom** [comment]
so the batch write takes about the same length of time as lots of individual write calls?

**Comment by LukasKStavario** [comment]
I think it is the same problem.

**Comment by LukasKStavario** [comment]
any news on this problem? its hot for me :D :/

**Comment by beachtom** [comment]
This should now be fixed

**Comment by LukasKStavario** [comment]
Looks good - I am able to rewrite my big model, thank you very much!
